### ISSUE TITLE
substitute_variables(strict = FALSE) no longer working that well

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqbc#151]
With the increase in the number of variables the strict = FALSE setting of substitute variables is no longer performing that well.

```r
substitute_variables(c("Iron Total", "Iron Dissolved", "Aluminum"), strict = FALSE)
[1] NA                                      "Dissolved Solids (Filterable Residue)" NA  
```

Should we deprecate the strict argument?

**Comment by joethorley** [comment]
What do you think @HeatherGranger?

**Comment by HeatherGranger** [comment]
Agree @joethorley. I believe this is what is behind the 'Strict matching' argument in the tidy tab in shinyrems and noticed when it was not checked (strict = FALSE) i'm assuming, the data would disappear. Given the number of variables, knowing exactly what the user wants to view makes sense. Let's remove the argument.
