### ISSUE TITLE
ncen table edit

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/wqbc#170]
Suggestion for improvement and clarification: 

I am wondering about modifying the ncen column so that is shows the number of censored observations regardless of whether the user opts for the ml summary stats estimation. Right now when you use summarise_wqdata(x, censored=FALSE) the ncen automatically defaults to 0. I think it makes more sense to still provide the ncen as the numbers of observations where the Value <= Detection Limit.

**Comment by joethorley** [comment]
@HeatherGranger - did you mean to close this issue?

**Comment by HeatherGranger** [comment]
@joethorley Yes - I added it to shinyrems repo, I think it fits there better for potential future opportunity.
