### ISSUE TITLE
Import data from EMS and lab standard formats

### ISSUE THREAD

**Issue by ateucher** [bcgov/wqbc#51]
- Provide instructions for EMS export
- Function `read_wq_data`(file = x, source = c("EMS", "ALS"))`

**Comment by ateucher** [comment]
Deal with embedded units in parameter name

**Comment by stephhazlitt** [comment]
Is this issue resolved with use of [rems](https://github.com/bcgov/rems)?

**Comment by ateucher** [comment]
The EMS part is. I'm not sure how important being able to read lab format is... I'll find out

**Comment by ateucher** [comment]
@HeatherGranger, is it important that `wqbc` be able to easily import data in the format provided directly by the lab(s), or will it mostly be in EMS, and thus we can pull it in via `rems`?

**Comment by HeatherGranger** [comment]
@ateucher The lab puts data into EMS and also sends an excel spreadsheet to whatever MOE biologist needs the data. I know the bio's usually work from these speadsheets, but for the sake of wqbc, it makes sense to just pull in the data with rems as each individual data spreadsheet from the lab would be different. I'm 95% sure that this is how it works in talking with different bio's, but I would confirm with Joyce Austin (MOE's lab manager) to make sure the lab's put all the data in EMS.

**Comment by ateucher** [comment]
That’s great, thanks @HeatherGranger. We can close this for now then unless people start asking to be able to import the lab format(s).

**Comment by ateucher** [comment]
That’s great, thanks @HeatherGranger. We can close this for now then unless people start asking to be able to import the lab format(s).

**Comment by ateucher** [comment]
That’s great, thanks @HeatherGranger. We can close this for now then unless people start asking to be able to import the lab format(s).

**Comment by ateucher** [comment]
That’s great, thanks @HeatherGranger. We can close this for now then unless people start asking to be able to import the lab format(s).
