### ISSUE TITLE
wqbc is failing because the wq package is not available

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqbc#53]
The solution I think is to

```
Set the environmental variable _R_CHECK_FORCE_SUGGESTS_ to a false value in Travis
```

**Comment by ateucher** [comment]
It's actually been archived on CRAN: ﻿https://cran.r-project.org/web/packages/wq/index.html. Can it be removed from `Suggests`?

**Comment by joethorley** [comment]
It was on CRAN but then Alan Jassby asked for it to be “archived” i.e. taken off CRAN which means it is no longer available anywhere.

We can remove all reference to it in wqbc but it was a valuable test set.

**Comment by joethorley** [comment]
I simply removed the dependency from the DESCRIPTION and wqbc passes all checks - its inclusion must have been due to some legacy changes
