### ISSUE TITLE
Allow Specification of Custom Limits

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/wqbc#56]
Let the user pass in custom water quality parameter limits, including where limits may be seasonal, site-specific, or dependent on other parameters.

**Comment by joethorley** [comment]
The function `calc_wqi` performs a number of tasks.  The first of these is to check if the dataset contains user defined limits in columns called `UpperLimit` or `LowerLimit`.  If the dataset has these columns, the function proceeds directly to calculating the water quality index.  

In other words the user can pass in custom limits.

**Comment by stephhazlitt** [comment]
I have used the above approach and it works well. I am also wondering about having the ability to pass in a dataframe with site-specific limits, some of which would be seasonal or dependent on other parameters. Passing in a user-supplied dataframe might mean less maintenance for the package and might give the package more flexibility for use outside of BC or for other wq analyses. With user-defined limits, the behavior might be something like check in user-defined limits table first, then in wqbc limits table, then error if no limit for parameter found?

**Comment by joethorley** [comment]
I think this is a good idea.

I think drop the offending variables with warning if no limit found is better than error because at least some progress can be made.

**Comment by joethorley** [comment]
Having reviewed this further I think this would be alot of work and would require the user to understand how to make up a limits table. Also I think the main functionality is covered by a calc_limits function that retains rows that already have limits.
