### ISSUE TITLE
Wrapper on rems

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqbc#62]
I think this would be very helpful.
It could be called get_wqdata() and it could take a data frame with columns EMS_ID and EMS_CODE to indicate which combinations of sites and codes to get. Values <= DetectionLimits could be set to zero - which is there true value.

**Comment by joethorley** [comment]
b. Add a `rems` wrapper function to `wqbc` such that data imported using `rems` is readied for use by `wqbc`. Specifically: rename columns, globally set values for when values are less than and/or equal to minimum detection limits, change negative temperature values to zero, allow user to remove columns not needed for `wqbc`, set appropriate date format, add Upper Limit and Lower Limit columns.

**Comment by ateucher** [comment]
@joethorley What date format is preferred? Right now I think it's `POSIXct`

**Comment by joethorley** [comment]
That's my go to

**Comment by joethorley** [comment]
I'll use that unless you have any objections

**Comment by ateucher** [comment]
Nope, that's great, you probably don't have to do anything to it then

**Comment by stephhazlitt** [comment]
I think the 'set date format' came from me. I found that I had to glean out the time part of the date column from the data frame sourced using rems?

**Comment by joethorley** [comment]
@stephhazlitt - see the following tweet illustrating why one should not use as.Date

https://twitter.com/joe_thorley/status/690577674389983233

lubridate::date doesn't have the same unexpected behaviour

**Comment by stephhazlitt** [comment]
Good to know, thanks @joethorley

**Comment by joethorley** [comment]
Do folks still think I should set negative temperatures to be zero - this concerns me since it may be hiding problems in the data?

**Comment by joethorley** [comment]
Also what is the reason for adding the Upper Limit and Lower Limit columns?

**Comment by ateucher** [comment]
Also just a note on timezones. As far as I know, all data in EMS is in PST - even the stations in the NE - and don't use daylight savings. The correct timezone string is `"Etc/GMT+8"`

**Comment by HeatherGranger** [comment]
@joethorley Is there a lot of negative temperature values do you know? Technically water freezes at 0 C but I think it's reasonable that a fast moving river could have a temperature of negative 1 or 2, so setting it to zero doesn't really make sense; can we just leave it as it's measured negative value? If there's temp data for -10 C, I would delete the data point before I would set it at zero. 

I think adding the Upper Limit and Lower Limit columns was for being able to manually add limits to those columns if needed?

**Comment by joethorley** [comment]
implemented as a `tidy_ems_data` plus another wrapper `tidy_ec_data`.
Option to keep variables with no limits will be added to later function.
