### ISSUE TITLE
Vignette failing

### ISSUE THREAD

**Issue by colinpmillar** [bcgov/wqbc#64]
The following error results in a failed check.  I have set eval=FALSE for now in order to allow other bits of the package to be checked.

```r
data(fraser)
data2012 <- subset(fraser, year(Date) == 2012)
data2012 <- standardize_wqdata(data2012)
## Standardizing water quality data...
## Deleted 45 rows with negative values in Value.
## Error in wqbc_substitute(org = x, mod = y, sub = sub, sub_mod = sub_mod,  : 
##  Nitrate Dissolved has multiple matches
```

**Comment by colinpmillar** [comment]
The problem seems to be that both "nitrate dissolved" and "nitrogen dissolved" are matched to "nitrogen dissolved nitrate" by `all_words_in_x_in_y_one`

```r
y <- tolower(as.character(unique(wqbc::fraser$Variable)))
y <- y[grep("nitrogen", y)]

# matching nitrate dissoved gives
y[apply(cbind(x = "nitrate dissolved", y = y), MARGIN = 1, wqbc:::all_words_in_x_in_y_one)]
## [1] "nitrogen dissolved nitrate"

# matching nitrogen dissolved also matches to "nitrogen dissolved nitrate"
y[apply(cbind(x = "nitrogen dissolved", y = y), MARGIN = 1, wqbc:::all_words_in_x_in_y_one)]
## [1] "nitrogen dissolved no3 & no2"        "nitrogen total dissolved"           
## [3] "nitrogen dissolved kjeldahl"         "nitrogen dissolved organic (calcd.)"
## [5] "nitrogen dissolved nitrate"  
```

**Comment by joethorley** [comment]
Fixed - substitute variable now returns NA when multiple matches

previously threw an error which scuppered everything

**Comment by HeatherGranger** [comment]
I'm getting this same error for 'ammonia dissolved' and 'nitrite dissolved'. I've reloaded the package.

> standard <- standardize_wqdata(all_data_filter)
Standardizing water quality data...
Deleted 94 rows with missing values in Value.
Deleted 128 rows with negative values in Value.
Error in wqbc_substitute(org = x, mod = y, sub = sub, sub_mod = sub_mod,  : 
  Ammonia DissolvedNitrite Dissolved has multiple matches

**Comment by joethorley** [comment]
I'm pretty sure I've fixed it in the outlier branch of wqbc.

Can you reinstall with
```
devtools::install_github("bcgov/wqbc@outlier_detection")
```

and let me know if this fixes it

**Comment by HeatherGranger** [comment]
Yes that worked, thanks Joe. 

Do parameters fail to substitute when they do not have an associated limit? 
'Alkalinity pH 4.5/4.2' shouldn't be substituted to pH, it can be deleted, doesn't look like that is measured anymore.
'Aluminum Total' should also be substituted to 'Aluminium Total' similar to the dissolved portion. 
Is there a way to tell what parameter had the inconvertible units?
Does standardize_wqdata change any units, or just convert from UG/L --> ug/L, MG/L --> mg/L ?

Standardizing water quality data...
Deleted 94 rows with missing values in Value.
Deleted 128 rows with negative values in Value.
Substituted 'Alkalinity pH 4.5/4.2' with 'pH', 'Alkalinity Total 4.5' with 'Alkalinity Total', 'Aluminum Dissolved' with 'Aluminium Dissolved', 'Hardness Total (Extractable)' with 'Hardness Total', 'Nitrate (NO3) Dissolved' with 'Nitrate Dissolved', 'Nitrogen (Kjeldahl) Total Dissolved' with 'Nitrogen Dissolved', 'Nitrogen Total Dissolved' with 'Nitrogen Dissolved' and 'Phosphorus Total Dissolved' with 'Phosphorus Dissolved'.
Failed to substitute 'Alkalinity Phen. 8.3', 'Aluminum Extractable', 'Aluminum Total', 'Antimony-Extractable', 'Antimony Dissolved', 'Antimony Total', 'Arsenic Extractable', 'Barium Extractable', 'Beryllium Dissolved', 'Beryllium Extractable', 'Beryllium Total', 'Bismuth Dissolved', 'Bismuth Extractable', 'Bismuth Total', 'Boron Extractable', 'Bromide Dissolved', 'Cadmium Extractable', 'Calcium Dissolved', 'Calcium Extractable', 'Calcium Total', 'Carbon Dissolved Inorganic', 'Carbon Dissolved Organic', 'Carbon Total', 'Carbon Total Dissolved', 'Carbon Total Inorganic', 'Carbon Total Organic', 'Cerium Dissolved', 'Cerium Extractable', 'Cerium Total', 'Cesium Dissolved', 'Cesium Extractable', 'Cesium Total', 'Chromium Extractable', 'Cobalt Extractable', 'Coliform - Fecal', 'Color Apparent', 'Color S./W. Diss.', 'Color TAC', 'Color True', 'Copper Extractable', 'Cyanide WAD', 'Cyanide(SAD) + SCN', 'Dissolved Oxygen-Field', 'E Coli', 'Gallium Dissolved', 'Gallium Extractable', 'Gallium Tota... <truncated>
Deleted 19742 rows with missing values in Variable.
Standardized water quality data.
Warning message:
In convert_values(x$Value, from = x$Units, to = codes$Unit, messages = messages) :
  1 values have inconvertible units

**Comment by joethorley** [comment]
Hi Heather

The substitution process is just based on the names i.e. it does not require a limit.

The substitution of Alkalinity pH 4.5/4.2 with pH is due to the matching algorithm which has to weigh matching things that shouldn't match with failing to match things that should match. Ideally the codes would be used but as they are generally not wqbc may need help. i.e. in this case Alkalinity pH 4.5/4.2 should be eliminated by the user prior to standardizing. 

Aluminimum Total is not standardized as it is not currently recognized by wqbc because we have no limits for it.

Is there a way to tell what parameter had the inconvertible units?
Not currently through wqbc. You could print all the unique units in the data frame and look for the oddity.

It converts from UG/L -> ug/L etc and then scales so consistent with wqbc i.e. ug/L * 1000 -> mg/L

**Comment by HeatherGranger** [comment]
Ok thanks Joe, that's helpful.
