### ISSUE TITLE
Add RESULT_LETTER column to tidy_ems_data

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/wqbc#69]
To confirm value units match detection limit units. Values that are set to zero should then have "<" in RESULT_LETTER column.

**Comment by ateucher** [comment]
Great idea. I wonder if we should include a certain set of columns by default (including RESULT_LETTER), and also allow a user to provide additional columns they would like to keep?

**Comment by ateucher** [comment]
@HeatherGranger a couple of questions about the `RESULT_LETTER` column:

1. what does `"M"` mean?
2. What to do when `RESULT_LETTER == ">"`
3. There are cases where the detection limit is `NA`, but `RESULT_LETTER` is `"<"`. Should we use the `RESULT_LETTER` column and set the `Value` to zero?

**Comment by HeatherGranger** [comment]
@ateucher 
1. "M" indicates 'equal to'. Just found this out. I guess rather than having NA in the RESULT_LETTER column if the value is greater than the detection limit it means the value is equal to 'X'. So no action needed if there's an "M". 
2. The RESULT_LETTER with the > sign looks to refer to maxing out the instrument, too high to count microbial counts etc. Appears to mainly be in wastewater, drinking water. I don't have any in my dataset for the fed/prov site at the Peace River, so I don't think we'll have to deal with these with river water quality data. If we did encounter these, I would take them out because we don't actually know what the value is as the instrument couldn't read it. 
3. When DETECTION LIMIT is "NA", and RESULT_LETTER is "<", I think we have to assume the VALUE is the same as the DETECTION LIMIT and yes, set this VALUE to zero. 

I see instances just looking through the raw dataframe where the VALUE is less than the DETECTION LIMIT but the RESULT_LETTER is NA. This would make sense if the DETECTION LIMIT are still in ug/L and never converted to mg/L along with the VALUES. I'm not sure now if this will be easier to identify once the < detection limit values are changed to zero....we may need to pull out all the rows where the values are less than the associated detection limit, with the RESULT_LETTER column and double check that there is actually a '<' sign in the column.

**Comment by HeatherGranger** [comment]
I also think it makes sense to allow users to choose a specific subset of columns with tidy_ems_data.

**Comment by ateucher** [comment]
Thanks! I'll push up something for you to test soon.

**Comment by ateucher** [comment]
Should be good to go (0abacc7e382baa61565dbd4819f7c5ba2618b036). Thanks for the help.

**Comment by HeatherGranger** [comment]
Thanks @ateucher, appreciate it. I'll test it out asap.
