### ISSUE TITLE
Changing units?

### ISSUE THREAD

**Issue by atillmanns** [bcgov/wqbc#70]
Somewhere in this package is there code for changing units of the parameters?  e.g. the ability to select parameters reporting out in ug/L and change this to mg/L?  Could you please point me to that section of code?

Thanks!

**Comment by joethorley** [comment]
https://github.com/bcgov/wqbc/blob/master/R/units.R

An alternative approach is to use https://cran.r-project.org/web/packages/udunits2/index.html

**Comment by ateucher** [comment]
@atillmanns did this help you solve your problem?

**Comment by ateucher** [comment]
I will start by exporting the `convert_values` and add a few examples.

**Comment by ateucher** [comment]
@atillmanns You can use the `convert_values` function now like this:

``` r
library(wqbc)

convert_values(1, "ug/L", "mg/L", messages = FALSE)
#> [1] 0.001

df <- data.frame(value = c(1.256, 5400000, 12300, .00098),
                 units = c("mg/L", "ng/L", "ug/L", "g/L"),
                 stringsAsFactors = FALSE)
df
#>       value units
#> 1 1.256e+00  mg/L
#> 2 5.400e+06  ng/L
#> 3 1.230e+04  ug/L
#> 4 9.800e-04   g/L

df$units_mg_L <- convert_values(df$value, from = df$units, to = "mg/L", messages = FALSE)
df
#>       value units units_mg_L
#> 1 1.256e+00  mg/L      1.256
#> 2 5.400e+06  ng/L      5.400
#> 3 1.230e+04  ug/L     12.300
#> 4 9.800e-04   g/L      0.980
```

cc @HeatherGranger
