### ISSUE TITLE
Retain EMS_ID column in clean_wqdata function

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/wqbc#71]
Helpful for plotting clean data for multiple sites at the same time.

**Comment by ateucher** [comment]
@HeatherGranger if you specify the EMS_ID column name in the `by` argument of `clean_wqdata()`, i think it should retain it. Can you give it a try? I.e. `clean_wqdata(mydata, by = "EMS_ID", ...)`

**Comment by HeatherGranger** [comment]
@ateucher yes! it works. thanks.

**Comment by ateucher** [comment]
Awesome! I'll add a bit to the document to make it a bit clearer.
