### ISSUE TITLE
clean_wqdata removes "Residue" parameters

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/wqbc#75]
`clean_wqdata` removes the following parameter codes and parameter name:

0005: Residue: Total (Total Solids)
0007: Residue: Filterable 1.0u (TDS)
0008: Residue: Non-filterable (TSS)
0009: Residue: Fixed Non-filterable (TSS, Fixed)
0010: Residue: Volatile Non-filterable (TSS, Volatile)
RF-F: Residue: Fixed Filterable (TDS, Fixed)
VFR: Residue: VolatileFilt (TDS, Volatile)

**Comment by ateucher** [comment]
Closing as is the same general issue as #76.
