### ISSUE TITLE
parameter 'color true' unit

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/wqbc#77]
Low priority item

EMS parameter 'color true' has units of Col.unit which get changed to CU during `clean_wqdata`. 
The actual units should be TCU (total colour units).
This may be an EMS issue if it's annoying to change in the `clean_wqdata` function.

**Comment by ateucher** [comment]
Working in the `col-units` branch - I changed everything to "Col.units" as that is what is in EMS... Where do you see/use "TCU"?

**Comment by HeatherGranger** [comment]
Col.units def works as that is what EMS says.

TCU is just the current units that true colour are described in. So not in EMS, just an 'expert piece of info' I guess?!

**Comment by ateucher** [comment]
Gotcha, thanks. I think I'll leave it as Col.unit as that is what will be coming from EMS.

If you get a chance, can you try it out? You can install with:

`devtools::install_github("bcgov/wqbc", ref = "col-units")`

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maintenance](https://trello.com/c/GTyxJtSb/13-maintenance)

**Comment by HeatherGranger** [comment]
@ateucher Successful trial of Col.unit !
