### ISSUE TITLE
refactor dplyr code for tideyeval framework

### ISSUE THREAD

**Issue by ateucher** [bcgov/wqbc#80]
dplyr 0.7 has hit the streets with big changes to dealing with non-standard evaluation - a new system called tidyeval. See `vignette("programming")`.

This isn't urgent yet, as the underscored versions of the dplyr verbs are deprecated, but not defunct (yet).

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maintenance](https://trello.com/c/GTyxJtSb/13-maintenance)

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maintenance](https://trello.com/c/GTyxJtSb/13-maintenance)

**Comment by joethorley** [comment]
My understanding is this is complete
