### ISSUE TITLE
tidy_ems_data should retain more columns

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/wqbc#83]
Add `SAMPLE_STATE` and `SAMPLE_DESCRIPTOR` to default set of columns that are retained, and add an argument `retain_cols` where a user can pass a character vector of additional column names to retain.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [wqbc::Enhancement](https://trello.com/c/nDBQgVhA/11-wqbcenhancement)

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [tidy_ems_data should retain more columns](https://trello.com/c/K39u8Ehi/38-tidyemsdata-should-retain-more-columns)

**Comment by ateucher** [comment]
Also document the default columns that are retained

**Comment by KaPrz** [comment]
Also please include SAMPLE_CLASS column as this indicates whether it is a regular sample, replicate, or blank
