### ISSUE TITLE
clean_wqdata should keep only water quality data

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/wqbc#84]
Dependent on completion of #83. Keep rows where `SAMPLE_STATE == c("Fresh Water", "Ground Water", "Wastewater", "Marine Water")`

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [clean_wqdata should keep only water quality data](https://trello.com/c/wvowVTWJ/37-cleanwqdata-should-keep-only-water-quality-data)

**Comment by ateucher** [comment]
@KaPrz would this set of `SAMPLE_STATE`s make sense to you or too restrictive? You mentioned you were working on sediment as well...

**Comment by KaPrz** [comment]
@ateucher it wouldn't make sense to retain sediment when doing any of the analysis (like calculating guidelines) or for the WQ Index, but it is nice to retain sediment through at least tidy_ems_data function.

**Comment by ateucher** [comment]
Ok, thanks @KaPrz  - so `tidy_ems_data()` will keep all `SAMPLE_STATE`s, but `clean_wq_data()` will keep only the above list.

**Comment by ateucher** [comment]
I think this is irrelevant for data from EC as it is only wq data already...

**Comment by KaPrz** [comment]
@ateucher I think it would be good to be able to use standardize_wqdata on sediment data as well. Pending some investigation into parameter names and codes.

**Comment by ateucher** [comment]
I think I'm going to close this one and leave it up to the user to filter the data before using `clean_wq_data()` etc. That way the user is : a) not constrained to what they can use it on, and b) forced to know exactly what data they're putting in.

So you can then

```r
library(dplyr)

sed_data <- filter(my_data, SAMPLE_STATE == "Fresh Water Sediment")
clean_wq_data(sed_data)

# OR 

fw_data <- filter(my_data, SAMPLE_STATE == "Fresh Water")
clean_wq_data(fw_data)
```

etc.
