### ISSUE TITLE
Manual unit change option other than `mutate`

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/wqbc#87]
Using `mutate` gives new column in DF. Useful for viewing converted values, but tricky when running summary stats as now have two Value columns. 
`all_data_clean <- mutate(all_data_clean, units_ugL = 
                           ifelse(Variable %in% c("Arsenic Total", "Cadmium Dissolved), Value*1000, NA))`

@ateucher Is it possible to use something like this below to replace the Value and Unit instead of a new column:

`all_data_clean <- ifelse(all_data_clean, Variable %in% 
                           c("Arsenic Total", "Cadmium Dissolved", "Cobalt Total",
                             "Copper Total", "Cyanide WAD", "Lead Total",
                           "Mercury Total", "Napthalene (C10H8)", "Nickel Total",
                            "Selenium Total", "Silver Total", "Thallium Total", "Toluene", 
                           "Uranium Total", "Zinc Total"), all_data_clean$Value*1000, all_data_clean$Value)`

`all_data_clean <- ifelse(all_data_clean, Variable %in% 
                           c("Arsenic Total", "Cadmium Dissolved", "Cobalt Total",
                             "Copper Total", "Cyanide WAD", "Lead Total",
                           "Mercury Total", "Napthalene (C10H8)", "Nickel Total",
                            "Selenium Total", "Silver Total", "Thallium Total", "Toluene", 
                           "Uranium Total", "Zinc Total"), all_data_clean$Units == "ugL", all_data_clean$Units)`

I get this error message : `Error in ifelse(all_data_clean, Variable %in% c("Arsenic Total", "Cadmium Dissolved": unused argument (all_data_clean$Units)`

**Comment by ateucher** [comment]
Close! You can overwrite an existing column in `mutate`. Try this:

```r
## Define your list of parameters once and use it repeatedly:
params_ug_L <- c("Arsenic Total", "Cadmium Dissolved", "Cobalt Total", "Copper Total", "Cyanide WAD", "Lead Total", "Mercury Total", "Napthalene (C10H8)", "Nickel Total", "Selenium Total", "Silver Total", "Thallium Total", "Toluene", "Uranium Total", "Zinc Total")

all_data_clean <- mutate(all_data_clean, 
    Value = ifelse(Variable %in% params_ug_L, Value * 1000, Value),
    Units = ifelse(Variable %in% params_ug_L, "ugL", Units))

```

**Comment by HeatherGranger** [comment]
Brilliant @ateucher. We have a go!
